FROM websphere-liberty:microProfile

RUN rm -rf /opt/ibm/wlp
COPY wlp /opt/ibm/wlp

# Install opentracing usr feature
RUN wget -t 10 -x -nd -P /opt/ibm/wlp/usr https://github.com/WASdev/sample.opentracing.zipkintracer/releases/download/1.1/liberty-opentracing-zipkintracer-1.1-sample.zip && cd /opt/ibm/wlp/usr && unzip liberty-opentracing-zipkintracer-1.1-sample.zip && rm liberty-opentracing-zipkintracer-1.1-sample.zip


COPY src/main/liberty/config/server.xml /config/server.xml
COPY /src/main/liberty/config/jvm.options.base /config/jvm.options
COPY /target/acmeair-authservice-java-2.0.0-SNAPSHOT.war /config/apps/


