FROM quay.io/wildfly/wildfly:latest-jdk11

# Enable Jaeger
ENV JAEGER_SERVICE_NAME=jaeger-service
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=false
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=0

COPY target/acmeair-authservice-java-5.0.war /opt/jboss/wildfly/standalone/deployments/
COPY src/main/liberty/config/resources/security/key.p12 /opt/boss/wildfly/

# Avoid annoying CDi INFO Message
RUN sed -i 's/<level name="INFO"/<level name="WARN"/' /opt/jboss/wildfly/standalone/configuration/standalone-microprofile.xml

USER 0
RUN chown jboss:0 /opt/jboss/wildfly/standalone/deployments/acmeair-authservice-java-5.0.war
RUN chown jboss:0 /opt/boss/wildfly/key.p12
USER jboss

ENV KEYSTORE_LOCATION=/opt/boss/wildfly/key.p12

ENV JAVA_OPTS="-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dhttp.keepalive=true -Dhttp.maxConnections=100"

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-c","standalone-microprofile.xml","-b", "0.0.0.0", "-bmanagement", "0.0.0.0","-Djboss.http.port=9080"]
