
# 1st stage, build the app
FROM maven:3.8.4-openjdk-17-slim as build

WORKDIR /helidon

# Create a first layer to cache the "Maven World" in the local repository.
# Incremental docker builds will always resume after that, unless you update
# the pom
ADD pom.xml_helidon ./pom.xml
RUN mvn package -Dmaven.test.skip -Declipselink.weave.skip

# Do the Maven build!
# Incremental docker builds will resume here when you change sources
ADD src src
RUN mvn package -DskipTests

RUN echo "done!"

COPY src/main/liberty/config/resources/security/key.p12 /helidon/target/key.p12


# 2nd stage, build the runtime image
FROM openjdk:17-jdk-slim
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY --from=build /helidon/target/acmeair-authservice-java.jar ./
COPY --from=build /helidon/target/libs ./libs
COPY --from=build /helidon/target/key.p12 /key.p12

ENV KEYSTORE_LOCATION=/key.p12

CMD ["java", "-jar", "acmeair-authservice-java.jar"]

EXPOSE 8080
