FROM tomee:9-jre11-microprofile

RUN rm -rf /usr/local/tomee/webapps/*
COPY target/acmeair-authservice-java-5.0.war /usr/local/tomee/webapps/ROOT.war
ENV JAVA_OPTS="-Dhttp.keepalive=true -Dhttp.maxConnections=100 -Dcom.acmeair.client.CustomerClient/mp-rest/url=http://acmeair-nginx1/customer"
RUN sed -i "s/8080/9080/g" conf/server.xml

COPY --chown=1001:0 src/main/liberty/config/resources/security/key.p12 /usr/key.p12
ENV KEYSTORE_LOCATION=/usr/key.p12

ENV JAEGER_ENABLEMENT=true
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=true
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=1
