FROM websphere-liberty:microProfile
RUN installUtility install  --acceptLicense logstashCollector-1.0
COPY server.xml /config/server.xml
COPY target/authservice-java-2.0.0-SNAPSHOT.war /config/apps/

ENV CUSTOMER_SERVICE=localhost:6379/customer

RUN wget -qO- https://github.com/amalgam8/amalgam8/releases/download/v1.0.0/a8sidecar.sh | sh
COPY config.yaml /opt/microservices/config.yaml

CMD [ "a8sidecar", "--config", "/opt/microservices/config.yaml" ]

