FROM quay.io/wildfly/wildfly:latest-jdk17

COPY --chown=jboss:0 target/acmeair-authservice-java-6.0.war /opt/jboss/wildfly/standalone/deployments/
COPY --chown=jboss:0 src/main/liberty/config/resources/security/key.p12 /opt/boss/wildfly/key.p12

ENV KEYSTORE_LOCATION=/opt/boss/wildfly/key.p12
ENV JAVA_OPTS="-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dhttp.keepalive=true -Dhttp.maxConnections=100"

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-c","standalone-microprofile.xml","-b", "0.0.0.0", "-bmanagement", "0.0.0.0","-Djboss.http.port=9080"]
