###### Main Service ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-auth-deployment
  template:
    metadata:
      labels:
        name: acmeair-auth-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: acmeair-authservice-java
        image: acmeair-authservice-java:latest
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: ACMEAIR_STACKAA_CUSTOMER_URL
          value: "http://acmeair-customer-service:9080/customer"
        - name: JAEGER_AGENT_HOST
          value: jaeger-all-in-one-inmemory-agent
        - name: JAEGER_AGENT_PORT
          value: '6832'
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-all-in-one-inmemory-collector:14268/api/traces'
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-auth-service
spec:
  ports:
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    name: acmeair-auth-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-secure-auth-service
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    name: acmeair-auth-deployment